// General-purpose game-icons for the entity type icon picker.
// These match the GI visual style and cover universal worldbuilding categories.
// All are pre-bundled in game-icons-mini.json for instant, offline rendering.
export const ICON_PICKER_OPTIONS = [
  // People & Characters
  "gi:cowled",
  "gi:two-shadows",
  "gi:hooded-figure",
  "gi:crown",
  "gi:coronation",
  "gi:crossed-swords",
  "gi:broadsword",
  "gi:magic-swirl",
  // Places & Locations
  "gi:position-marker",
  "gi:castle",
  "gi:guarded-tower",
  "gi:medieval-gate",
  "gi:mountains",
  "gi:forest",
  "gi:wood-cabin",
  "gi:camping-tent",
  "gi:stone-wall",
  "gi:globe",
  // Objects & Items
  "gi:chest",
  "gi:key",
  "gi:scroll-unfurled",
  "gi:spell-book",
  "gi:health-potion",
  "gi:blacksmith",
  "gi:shield",
  "gi:backpack",
  "gi:crystal-shine",
  "gi:boss-key",
  // Events & Time
  "gi:pocket-watch",
  "gi:hourglass",
  "gi:campfire",
  "gi:lightning-helix",
  "gi:sun",
  "gi:crescent-blade",
  "gi:star-formation",
  // Groups & Factions
  "gi:flag-objective",
  "gi:pirate-flag",
  "gi:linked-rings",
  "gi:world",
  "gi:price-tag",
] as const;

export type IconPickerOption = (typeof ICON_PICKER_OPTIONS)[number];

// Cross-genre curated default icons shown before a search is entered.
// All names are verified to exist in @iconify-json/game-icons and are
// bundled offline in game-icons-mini.json.
export const DEFAULT_GAME_ICONS = [
  // Fantasy
  "gi:dragon-head",
  "gi:broadsword",
  "gi:castle",
  "gi:wizard-staff",
  "gi:spell-book",
  "gi:goblin-head",
  "gi:wolf-head",
  "gi:crown",
  "gi:scroll-unfurled",
  "gi:magic-swirl",
  "gi:rune-stone",
  "gi:open-treasure-chest",
  "gi:vampire-dracula",
  "gi:werewolf",
  "gi:black-knight-helm",
  // Sci-Fi
  "gi:rocket",
  "gi:astronaut-helmet",
  "gi:alien-stare",
  "gi:battle-mech",
  "gi:cyber-eye",
  "gi:blaster",
  "gi:atom",
  "gi:circuitry",
  "gi:spaceship",
  "gi:ufo",
  "gi:laser-gun",
  "gi:android-mask",
  "gi:delivery-drone",
  "gi:beam-satellite",
  "gi:plasma-bolt",
  // Horror
  "gi:death-skull",
  "gi:ghost",
  "gi:grim-reaper",
  "gi:scythe",
  "gi:coffin",
  "gi:graveyard",
  "gi:crow-dive",
  "gi:candle-skull",
  "gi:hanging-spider",
  "gi:floating-tentacles",
  "gi:broken-skull",
  "gi:shambling-zombie",
  "gi:candle-flame",
  "gi:bleeding-heart",
  "gi:skull-mask",
  // Historical / Mythology
  "gi:ancient-sword",
  "gi:greek-temple",
  "gi:lighthouse",
  "gi:coins",
  "gi:compass",
  "gi:trident",
  "gi:cauldron",
  "gi:battle-axe",
  "gi:torch",
  "gi:plain-dagger",
  "gi:viking-head",
  "gi:minotaur",
  "gi:hydra",
  "gi:eagle-head",
  "gi:orc-head",
] as const;
